zhaofengli/colmena

src/nix/eval.nix
src/nix/host/local.rs
src/nix/host/ssh.rs
src/nix/key.rs

Allows uploading the contents of a local file as a key. Fixes #4.

Add 'deployment.keys.<key>.keyFile' option

---

src/nix/deployment.rs
src/nix/host/ssh.rs
src/nix/key.rs
src/nix/mod.rs
src/progress.rs

So I thought that it might be nice to log out a proper error if `keyCommand` fails. I also made it so the output is buffered. This way, the key is not partially written if the `keyCommand` fails in the middle. So there is no possibility to clobber an existing key with a malformed one.
Example output (non-existent `keyFile`):
Example output (`keyCommand = ["date" "-Ins" "foobar"]` (extraneous argument to the `date` command)):
If stderr contains multiple lines, it does not print out nicely, especially with the progress bar mode. Not sure how to deal with that.

Handle and report errors of key source, do not write out key if keyCommand failed

---

src/nix/eval.nix

This one is kinda hard to explain because nixpkgs internals are still a bit of a mystery to me.
Given a hive that looks something like this:
```nix
let
pkgs = builtins.fetchGit {
name = "nixos-20.09-2021-01-27";
url = "https://github.com/nixos/nixpkgs";
ref = "refs/heads/nixos-20.09-small";
rev = "02a184883e423ff2da75581518d3ed2efeb8577d";
};
in
{
network = {
nixpkgs = import pkgs {
config.allowUnfree = true;
};
};
machine = { ... }: { /* ... */ };
}
```
Colmena (or rather Nix) would give me errors:
```
Evaluation of 2 nodes failed. Last 10 lines of logs:
a) For `nixos-rebuild` you can set
{ nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.
b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
{ allowUnfree = true; }
to …
```

Propagate same 'pkgs' to all modules

---

src/nix/host/ssh.rs

The targetPort option for a deployment was ignored when copying closures. Using the same NIX_SSHOPTS env info seems to be working, but maybe there's a cleaner/preferred way to handle it.

Makes SSH options available to nix-copy-closure

---

README.md
src/command/apply.rs
src/nix/deployment.rs
src/nix/eval.nix
src/nix/host/local.rs
src/nix/host/mod.rs
src/nix/host/ssh.rs
src/nix/mod.rs

Adds a `deployment.replaceUnknownProfiles` option and `--ignore-replace-unknown-profiles` option flag to the cli
If `deployment.replaceUnknownProfiles` is set to false, a diverged hive config (in a shared git repo for example) won't result in accidentally undoing another applied configuration profile. Just moving back and forth between my desktop and laptop I managed to replace a profile because I forgot to commit and push changes on one machine.
The deployment option `deployment.replaceUnknownProfiles` default is true so that fiction is minimized from aggressive nix store garbage collection, first time profile application, etc. If a hive is being modified across a large team, it's probably best to just use CI/CD, so this option mostly exists for single user and small teams who might …

Warn on unknown remote profiles replacement, error out if node-level option is explicitly enabled

---

flake.nix
src/nix/hive/eval.nix

Allow flake users to import .#nixosModules.deploymentOptions
into their flake, so that the same expression can be used for both,
.#colmena.$host as well as .#nixosConfigurations.$host, without the
latter complaining about undefined options in "deployment".
Tests seem to pass, building the manual still works and the resulting nixosModules.deploymentOptions works as expected in my configration. What do you think?
(reusing the same attrset for nixosConfigurations and colmena hosts only really works for setups which don't use the name and nodes parameters)

eval.nix: expose nixosModules.deploymentOptions

---

src/nix/deployment/mod.rs
src/nix/evaluator/mod.rs
src/nix/evaluator/nix_eval_jobs.rs

I'm not sure if use of a public field is the most elegant way to implement this, but I thought I'd throw this over the fence as a minimal working implementation :)

streaming evaluator: respect eval-nodes-limit

---

integration-tests/apply/test-script.py
integration-tests/tools.nix
manual/src/features/keys.md
src/nix/hive/eval.nix

eval.nix: Add "${name}-key.service" units for keys

---

src/command/apply_local.rs

This fixes apply-local not detecting the system as NixOS due to the changes in the format of the `os-release` file.
Details on the changes made to the `os-release` file can be found in the following commit https://github.com/NixOS/nixpkgs/commit/bae181d3f0f453d9a23cf5e899c2cb0f96e91fef.
I'm new to Rust so let me know if I've missed anything, thanks!

apply_local: Fix nixos detection from os-release

---

.github/workflows/build.yml
flake.lock

- ci: remove unused Nix versions in build stage
- ci: upgrade to Nix 2.8.0 for build and test
- ci: update cachix/install-nix-action to v17

Use new Nix for CI

---

flake.nix
src/nix/hive/eval.nix
src/nix/hive/mod.rs
src/nix/hive/modules.nix
src/nix/hive/options.nix

- the reason for this change is to have more transparent separation
of concern between effectuations of the module system and pre-module
system effectuations
- with improved flakes support down the line, pre-module system
effectuations will get more complex
- this also allows to patch the aspects of the evaluation individually while
tracking other components from upstream. eg. patch options & eval but
not modules

imp: soc of eval, modules & options

---

Cargo.lock
Cargo.toml
package.nix
src/nix/host/ssh.rs
src/nix/mod.rs

Right now colmena will statically emit the current user in the `user@host` target, preventing the usage of .ssh/config or equivalent of overriding the username.
In situations where a repository is shared with multiple people such that configuring deploymentUser in the repository is unfeasible, this makes it easier when certain remote machines demand a particular user that is different from the local user.
This also addresses #61

Do not use an explicit user for ssh when deploymentUser is null

---

integration-tests/allow-apply-all/default.nix
integration-tests/allow-apply-all/hive.nix
integration-tests/default.nix
manual/src/release-notes.md
src/command/apply.rs
src/nix/hive/eval.nix
src/nix/hive/mod.rs
src/nix/hive/options.nix
src/nix/hive/tests/mod.rs
src/nix/mod.rs

close https://github.com/zhaofengli/colmena/issues/95
This PR also add metaConfig struct for `hive.meta` section.

feat(meta): add disallowApplyAll options

---

src/nix/hive/eval.nix
src/nix/hive/options.nix

This adds `meta.nodeSpecialArgs` which follows the same semantics as `meta.nodeNixpkgs` but for the `specialArgs` passed into evaluation.

eval.nix: per-node specialArgs

---

src/cli.rs
src/command/apply_local.rs
src/nix/deployment/mod.rs
src/nix/evaluator/mod.rs
src/nix/evaluator/nix_eval_jobs.rs
src/nix/hive/mod.rs
src/nix/host/local.rs
src/nix/mod.rs
src/util.rs

I use this to pass `extra-builtins-file`, but thought it would be more useful to add a generic flag.
An other solution would be forwarding any extra args to nix: `colmena build --verbose -- --option name value`.  
If that sounds better I can do that!
I also renamed `NixOptions` to `NixFlags` to help differentiate in the code between Nix's `--option` and other CLI
flags (previously referred to as options). This is a separate commit and can be squashed/dropped/left as is if you want.
I could also rename the other `*Options` types if you'd like.

 cli: Add --nix-option to allow passing arbitrary nix options 

---

integration-tests/apply/test-script.py
src/nix/hive/modules.nix

Resurrecting #116.  It looks, from testing, the systemd path units aren't actually reliable for triggering when files are created.  So they'll work fine if you use them on keys that are configured to a `destDir` such that the keys exist on boot, but they won't work consistently if you boot and then use `colmena upload-keys`.
This PR replaces the systemd path based implementation with the proven-reliable implementation from nixops.  I literally copy-pasted the unit configuration over from [here](https://github.com/NixOS/nixops/blob/master/nix/keys.nix#L235-L261).
I've confirmed on my own configs that this fixes all the problems I was having with the reliability of the key services.  However, I haven't yet put together a minimal repro.  I could work on doing that if you felt it was …

Use nixops implementation of key services

---

src/nix/hive/eval.nix

In the warning for flakes which are using an uninitialized nixpkgs the builtin variable `currentSystem` is accessed, which is impure and leads to an error. This PR replaces the variable with a static hint.

Remove usage of impure variable `builtins.currentSystem` in eval.nix when using flakes

---

flake.nix

Without this, users are greeted with https://github.com/numtide/nixpkgs-unfree/blob/main/default.nix
When they use `nixpkgs-unfree` like this: https://gitlab.com/dar/home-nix/-/blob/main/flake.nix#L9-10
(and align colmena's `nixpkgs` version like this: https://gitlab.com/dar/home-nix/-/blob/main/flake.nix#L25-28)

fix: 1000 nixpkgs; compat with numtide/nixpkgs-unfree

---

src/nix/host/ssh.rs

This patch fixes the substitution (e.g. `cache.nixos.org`) on remotes when deploying a flake-based `colmena` hive, which implies the use of the experimental `nix3 copy` (since 7fac0278e196ff52cfa2622f62cbbca462db12d5).
I consider this a UX bug in `nix` and its `ssh-ng://` itself.
I _think_ this is because `ssh-ng://` simply hasn't implemented `--substitute-on-builders` yet.
`--builders-use-substitutes` works, however (https://github.com/NixOS/nix/pull/4180).
The old/legacy `ssh://` does not have this issue with `nix3 copy`.
I'll try to look a bit more into this in the future and will consider submitting a patch in upstream.
But for now, this patch should suffice.
Especially considering it will take quite some time until that patch is available in a new `nix` release and installed on …

ssh: fix substitution when using experimental `nix copy`

---

src/nix/hive/eval.nix

This patch allows nodes to override `nodes` and `name` in their `specialArgs`, which is very useful to allow accessing more systems in case the flake defines other systems additional to colmena nodes.

fix: allow nodeSpecialArgs to override name and nodes

---

src/command/exec.rs
src/error.rs

Hello and thanks for your great software.
I'm interested in using `colmena exec <command>` from other scripts. It would be helpful if colmena returned a non-zero exit code if `<command>` fails on some hosts. In the current version from `nixos-23.11`, the exit code is always 0.
The proposed change achieves this. I'm neither proficient with rust nor have I spent much time reading the code. Feel free to rewrite if you see a more appropriate solution. Also looking forward to your comments.

Set exit code > 0 when colmena exec fails

---

src/nix/hive/options.nix
src/nix/host/ssh.rs
src/nix/mod.rs
src/nix/node_filter.rs

Configuration of SSH options has been wanted for a while: https://github.com/zhaofengli/colmena/issues/90
This patch adds a option on the node configuration to specify SSH options on a per-node basis. Extra SSH options are merged with the pre-defined list on the `ssh_options()` function.
I'm still not familiar with the colmena codebase, so please correct me if I make any mistakes.
Thank you for your great software and I look forward to feedback.

Support adding extra ssh options on node configurations

---

src/nix/hive/eval.nix

Currently the flake.nix already sets both of these options for lib.makeHive, but this makes it more convenient for non-flake users to also just directly use the eval.nix

make eval.nix more convnient to use for non-flake user

---

flake.lock
flake.nix
integration-tests/tools.nix
src/nix/hive/options.nix

`lib.mdDoc` emits this trace when called since 24.05:
```quote
trace: warning: lib.mdDoc will be removed from nixpkgs in 24.11. Option descriptions are now in Markdown by default; you can remove any remaining uses of lib.mdDoc.
```
Given that this was introduced with 22.11 and made obsolete in 24.05 with all prior versions being EoL at this point it should be safe to revert that change. In any case the only result will be that anything ≥22.11 and <24.05 will be rendered without markup which I guess isn't the best, but given those are EoL systems it's not the worst.
Either way it gets rid of a *lot* of noise for 24.05 users in the trace, and for 24.11 and up it will remove dead code.
This reverts commit 7602e548a78932bd28a7e2f621b3d62b4124e993.

lib.mdDoc has been deprecated since 24.05

---

src/job.rs

Colmena truncates left over node names when it reaches a certain char limit. This in it self is a sensible behaivior, but it should only do so if there is more then one node name remaining.

Fix describe_node_list remaining nodes special case

---

.github/workflows/build.yml
.github/workflows/linters.yml
.github/workflows/tests.yml
src/nix/hive/assets.rs

On macOS `/tmp` is a symlink to `/private/tmp`.
TempDir creates a dir and returns the path as `/tmp/...`. nix is unhappy with symlink dirs when calling `nix flake metadata --json path:...`
```
error (ignored): error: end of string reached
error:
… while fetching the input 'path:/tmp/colmena-assets-XHHAXJ'
error: path '/tmp' is a symlink
thread 'main' panicked at src/cli.rs:286:38:
Failed to get flake or hive: ChildFailure { exit_code: 1, backtrace:    0: backtrace::capture::Backtrace::new
1: colmena::nix::flake::FlakeMetadata::resolve::{{closure}}
2: colmena::nix::flake::Flake::from_uri::{{closure}}
3: colmena::cli::run::{{closure}}
4: tokio::runtime::park::CachedParkThread::block_on
5: colmena::main
6: std::sys_common::backtrace::__rust_begin_short_backtrace
7: …
```

resolve TempDir paths before passing them to the flake bin

---

Cargo.lock
Cargo.toml
src/progress/mod.rs

Fixes https://github.com/advisories/GHSA-g98v-hv3f-hcfr. The MSRV isn't an issue since we support the latest stable nixpkgs.

progress: Detect tty with std::io::IsTerminal, remove atty

---

flake.lock
flake.nix
integration-tests/tools.nix
nix-eval-jobs-stable.patch
nix-eval-jobs-unstable.patch

We carry a custom patch for nix-eval-jobs that causes the tool to not unset the `NIX_PATH` environment variable anymore. The patch does not apply anymore starting with d0bcdae (clang-tidy: use trailing return type, 2024-11-10) because surrounding code has changed. Other than that the patch still applies.
The mentioned commit was released with nix-eval-jobs v2.25.0, which nixos-unstable has recently upgraded to. Adapt the patch to unbreak the build.
Fixes #255.

flake: fix patch for nix-eval-jobs

---

package.nix

So that we can `nixpkgs.lib.getExe` without worry.

Add meta.mainProgram

---

Cargo.lock
Cargo.toml
src/cli.rs
src/command/apply.rs
src/command/apply_local.rs
src/command/eval.rs
src/command/exec.rs
src/nix/node_filter.rs

Related issue: https://github.com/zhaofengli/colmena/issues/260
This PR refactors our Clap command and argument definitions by moving the inline `help` and `long_help` attributes into Rust doc comments. The same thing was done with `about` and `long_about` attributes. While this causes slightly different output in a few places, it results in more readable and maintainable code overall.
Additionally, the `wrap_help` feature has been enabled to neatly format these doc comments in the CLI help text, and `Cargo.lock` now includes the terminal_size crate to support dynamic help wrapping.

Improve help message readability

---

src/nix/hive/mod.rs
src/nix/host/local.rs
src/nix/mod.rs

I noticed that setting `--nix-option extra-substituters ... --nix-option extra-trusted-public-keys ...` did not allow colmena to substitute things from an internal cache while building nodes. I eventually traced this to `Hive::nix_flags_with_builders` not including the options in the same way that `Hive::nix_flags` does. I did not immediately see any reason why `nix_flags_with_builders` should ever return fewer flags than `nix_flags`, so I just modified `nix_flags_with_builders` to start by calling `nix_flags`. If there's a reason that I'm not aware of, please let me know what it is, and I'll think about this some more.
There are two failing tests, but they were failing on `main`, too, so I don't think I caused the breakage.
I was able to build our configuration, hitting our internal …

Make nix_flags_with_builders call nix_flags

---

flake.nix

Set `__intentionallyOverridingVersion` = true to explicitly suppress the warning,
as we are intentionally changing the version without changing the src.
https://github.com/NixOS/nixpkgs/blob/bf8cde15eee43c9576ebc8ded247e4783736098f/pkgs/stdenv/generic/make-derivation.nix#L109-L129
```
evaluation warning: nix-eval-jobs-2.29.0 was overridden with `version` but not `src` at /nix/store/3diqksc2c5dl8517mq71pgyabxc250y5-source/flake.nix:37:9.
This is most likely not what you want. In order to properly change the version of a package, override
both the `version` and `src` attributes:
hello.overrideAttrs (oldAttrs: rec {
version = "1.0.0";
src = pkgs.fetchurl {
url = "mirror://gnu/hello/hello-${version}.tar.gz";
hash = "...";
};
})
(To silence this warning, set `__intentionallyOverridingVersion = …
```

fix(nix-eval-jobs): silence warning when overriding version without src

---

src/nix/hive/modules.nix

If you change the [name of a pre-activation key](https://colmena.cli.rs/unstable/reference/deployment.html#deploymentkeysnamename), Colmena will chown the wrong key path.

fix: Chown correct path for pre-activation keys

---

flake.nix

I disabled the overlay with the patched nix-eval-jobs when it's version < 2.30.0.
Fixes #302

Don't use patched version of nix-eval-jobs if version >= 2.30.0
